### PR TITLE
added paletteColorDim function

### PR DESCRIPTION
**Pull request by Ozzyboshi**
Dimming a single color can be very useful, in my case more than paletteDim.

### CODE REVIEW

**Comment by tehKaiN** [comment]
I think that having this fn as `UWORD paletteDimColor(UWORD uwColor, ubLevel)` wouldn't be better: you pass just reference color and brightness level, you get modified color in return.

Also, paletteDim should use this fn in a loop, I think.

**Comment by Ozzyboshi** [comment]
something like paletteColorDim( &s_pVp->pPalette[ubColIndex], (15 * fadeOut) / 50);

No more source and destination as parameters?
Source and destination are always the same thing with this approach.
What about a new inline function that calls paletteColorDim? Something like paletteColorChange( &s_pVp->pPalette[ubColIndex], (15 * fadeOut) / 50);
and inside just a regular call to paletteColorDim?

**Comment by tehKaiN** [comment]
I thought something like `uwNewColor = paletteColorDim(uwFullColor, ubFadeRatio)`

**Comment by Ozzyboshi** [comment]
I made a little change that shoud reflect what you asked.
This is a little example how to use it

UWORD s_pPaletteRef[32];
paletteLoadFromMem(PRES1_PALETTE_data, s_pPaletteRef, 1 << s_pVp->ubBPP);
UWORD uwFullColor = s_pPaletteRef[COLOR_INDEX];
UBYTE ubFadeRatio = (15 * fadeIn) / 50;
s_pVp->pPalette[TEXT_COLOR_INDEX] = paletteColorDim(uwFullColor, ubFadeRatio);

what do you think? is this what you planned to dim a single color?

**Comment by tehKaiN** [comment]
Yes, that's exactly it! Now I think you just need to refactor paletteDim() so that it will use paletteColorDim() so that we won't have too much code to maintain. ;)

**Comment by tehKaiN** [comment]
Okay, we're good to go!

**Pull request merged**
